services:
  - type: web
    name: companysearch
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install --with-deps
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
        
